### ISSUE TITLE
cases produces duplicates and does not produce every possible combination

### ISSUE THREAD

**Issue by imperialone** [quasar098/pwcrack-builder#1]
Using "cases" for any string produces duplicates nor does it create every possible combination.

Using the six-letter string 'abcdef' as an example, the possible number of combinations is 2^6 = 64.

"python pwcrack-builder.py cases abcdef.txt | wc -l" results in 1,555. "python pwcrack-builder.py cases abcdef.txt | sort | uniq | wc -l" results in 57.

**Comment by quasar098** [comment]
ncl player

**Comment by quasar098** [comment]
it produces only 57 because it does 1-4 letters caps

```
- lower case the entire word, then change 1-4 letters to capital (try all possibilities)
```
(from the readme)

ok there is a mistake in the next line that says `The_testing123` can turn into `tHe_tEsTiNG123` (this is not possible), i will probably not go fix it because i am supremely lazy

i cannot reproduce your reported error of 1555 lines from the "abcdef" file

```
user@computer:~/pwcrack-builder$ python3 pwcrack-builder.py cases example/abcdef.txt | wc -l
57
user@computer:~/pwcrack-builder$ xxd example/abcdef.txt
00000000: 6162 6364 6566
```

**Comment by imperialone** [comment]
I understand now, I misread that part about 1-4 letters because I focused on "try all possibilities". And also because enumleet does iterate all possibilities from my testing. My apologies.

**Comment by quasar098** [comment]
ok
